### ISSUE TITLE
CA bundle sync

### ISSUE THREAD

**Issue by chesteroni** [certifi/gocertifi#8]
Hello,

there is a statement in README that the CA bundle is the same as in requests library. However, 15 CAs are missing. There should be a sync or, preferably, automatic download from Mozilla.
Here are the missing certs' sha1 sums:
99:a6:9b:e6:1a:fe:88:6b:4d:2b:82:00:7c:b8:54:fc:31:7e:15:39
31:7a:2a:d0:7f:2b:33:5e:f5:a1:c3:4e:4b:57:e8:b7:d8:f1:fc:a6
e3:92:51:2f:0a:cf:f5:05:df:f6:de:06:7f:75:37:e1:65:ea:57:4b
87:9f:4b:ee:05:df:98:58:3b:e3:60:d6:33:e7:0d:3f:fe:98:71:af
69:bd:8c:f4:9c:d3:00:fb:59:2e:17:93:ca:55:6a:f3:ec:aa:35:fb
e5:df:74:3c:b6:01:c4:9b:98:43:dc:ab:8c:e8:6a:81:10:9f:e4:8e
da:40:18:8b:91:89:a3:ed:ee:ae:da:97:fe:2f:9d:f5:b7:d1:8a:41
7e:78:4a:10:1c:82:65:cc:2d:e1:f1:6d:47:b4:40:ca:d9:0a:19:45
62:7f:8d:78:27:65:63:99:d2:7d:7f:90:44:c9:fe:b3:f3:3e:fa:9a
23:e5:94:94:51:95:f2:41:48:03:b4:d5:64:d2:a3:a3:f5:d8:8b:8c
74:2c:31:92:e6:07:e4:24:eb:45:49:54:2b:e1:bb:c5:3e:61:74:e2
a1:db:63:93:91:6f:17:e4:18:55:09:40:04:15:c7:02:40:b0:ae:6b
85:37:1c:a6:e5:50:14:3d:ce:28:03:47:1b:de:3a:09:e8:f8:77:0f
97:81:79:50:d8:1c:96:70:cc:34:d8:09:cf:79:44:31:36:7e:f4:74
d2:32:09:ad:23:d3:14:23:21:74:e4:0d:7f:9d:62:13:97:86:63:3a

**Comment by Lukasa** [comment]
There is a sync.

Requests is the library that has diverged, not the other way around. In particular, Requests contains deprecated SHA-1 root certificates that have been removed from Mozilla's certificate bundle but have been preserved in Requests. They were preserved for fairly boring reasons, mostly to do with the fact that many Python scripts use old versions of OpenSSL that cannot tolerate cross-signed root certificates.

This problem does not exist in Go, as it uses its own crypto/tls stack, so there is no need to persist those deprecated and weak root certificates. That's why the bundles have diverged.
